version: '3.8'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=your_jwt_secret_key
      # Diğer gerekli ortam değişkenlerini buraya ekleyin
    volumes:
      - ./storage:/app/server/storage
      - ./storage/.env:/app/server/.env
    restart: always
